### ISSUE TITLE
Reporter modules crash on db connection error

### ISSUE THREAD

**Issue by thorgrin** [CESNET/Nemea-Modules#57]
All reporting modules crash when I stop MongoDB (to which they are configured to write).

I get the following error:

```
Traceback (most recent call last):
  File "/usr/bin/nemea/hoststats2idea.py", line 195, in <module>
    arg_parser = None # (optional) Instance of argparse.ArgumentParser with some arguments defined can be passed - these arguments are then parsed from command line and passed to the conv_func)
  File "/usr/lib/python2.7/site-packages/report2idea.py", line 141, in Run
    config = Config.Config(args.config, trap = trap, warden = wardenclient)
  File "/usr/lib/python2.7/site-packages/reporter_config/Config.py", line 59, in __init__
    self.actions[i["id"]] =  MongoAction(i)
  File "/usr/lib/python2.7/site-packages/reporter_config/actions/Mongo.py", line 34, in __init__
    self.client = pymongo.MongoClient(self.host, self.port)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 337, in __init__
    raise ConnectionFailure(str(e))
pymongo.errors.ConnectionFailure: could not connect to localhost:27017: [Errno 111] Connection refused
Exception AttributeError: "MongoAction instance has no attribute 'client'" in <bound method MongoAction.__del__ of <reporter_config.actions.Mongo.MongoAction instance at 0x128f830>> ignored
```

The expected behavior is to log the problem or be quiet about it, not crash.

**Comment by thorgrin** [comment]
Somewhere in the development process, this was fixed and is working fine now.
